### ISSUE TITLE
Can't see raid frames in social pane with weakaura addon in combat

### ISSUE THREAD

**Issue by fluffyst** [raethkcj/WeakAuras_2.4.3#5]
As title stated, when the addon is turned on the raid frame in social pane is just blank while in combat, works fine out of combat, it's 100% because of weakauras, big issue because it means I can't move groups around mid fight for lust, etc
https://puu.sh/GGgYw/f27cf87bc3.png

**Comment by fluffyst** [comment]
Trying to debug this myself:

```
10/28 03:59:39.190  An action was blocked in combat because of taint from WeakAuras - RaidFrame:Show()
10/28 03:59:39.190      Interface\FrameXML\FriendsFrame.lua:33 FriendsFrame_ShowSubFrame()
10/28 03:59:39.190      Interface\FrameXML\FriendsFrame.lua:194 FriendsFrame_Update()
10/28 03:59:39.190      Interface\FrameXML\FriendsFrame.lua:125
10/28 03:59:39.190      FriendsFrame_OnShow()
10/28 03:59:39.190      FriendsFrame:OnShow()
10/28 03:59:39.190      FriendsFrame:Show()
10/28 03:59:39.190      Interface\FrameXML\UIParent.lua:1341 <unnamed>:SetUIPanel()
10/28 03:59:39.190      Interface\FrameXML\UIParent.lua:1196 <unnamed>:ShowUIPanel()
10/28 03:59:39.190      Interface\FrameXML\UIParent.lua:1092
10/28 03:59:39.190      <unnamed>:SetAttribute()
10/28 03:59:39.190      Interface\FrameXML\UIParent.lua:1651 ShowUIPanel()
10/28 03:59:39.190      Interface\FrameXML\FriendsFrame.lua:945 ToggleFriendsFrame()
10/28 03:59:39.190      TOGGLESOCIAL:1
```

```
10/28 03:59:32.628  Execution tainted by WeakAuras while reading NORMAL_FONT_COLOR - Interface\FrameXML\FriendsFrame.lua:273
10/28 03:59:32.628      FriendsList_Update()
10/28 03:59:32.628      Interface\FrameXML\FriendsFrame.lua:124
10/28 03:59:32.628      FriendsFrame_OnShow()
10/28 03:59:32.628      FriendsFrame:OnShow()
10/28 03:59:32.628      FriendsFrame:Show()
10/28 03:59:32.628      Interface\FrameXML\UIParent.lua:1341 <unnamed>:SetUIPanel()
10/28 03:59:32.628      Interface\FrameXML\UIParent.lua:1196 <unnamed>:ShowUIPanel()
10/28 03:59:32.628      Interface\FrameXML\UIParent.lua:1092
10/28 03:59:32.628      <unnamed>:SetAttribute()
10/28 03:59:32.628      Interface\FrameXML\UIParent.lua:1651 ShowUIPanel()
10/28 03:59:32.628      Interface\FrameXML\FriendsFrame.lua:945 ToggleFriendsFrame()
10/28 03:59:32.628      TOGGLESOCIAL:1
```

There is a lot more in my taint log, which you can get easily with `/console taintLog 2` but basically it looks like the global vars in https://github.com/raethkcj/WeakAuras_2.4.3/blob/master/WeakAuras/!compatibility/Constants.lua are causing a conflict.

Commenting out this entire file seemed to fix the issue, didn't seem to break any of my current auras either, are they used for anything?

**Comment by raethkcj** [comment]
I didn't write this addon, I'm simply maintaining it, so I can't be 100% sure what their intended purpose was. As long as all those constants are defined in FrameXML, shouldn't be any issue deleting them.

**Comment by raethkcj** [comment]
Some of them are not duplicates; removed only the duplicates for now.

bdc2124

**Comment by raethkcj** [comment]
Taint issues should be fixed in branch [taint](/raethkcj/WeakAuras_2.4.3/taint), mind checking to confirm?

**Comment by fluffyst** [comment]
Yeah I just was looking at that myself, I fixed it by making `RAID_CLASS_COLOR` a local variable, testing your version seems to work too though! Testing with myself and +1 outside shat just hitting a mob
