### ISSUE TITLE
aura_env implementation?

### ISSUE THREAD

**Issue by Foodlenz** [raethkcj/WeakAuras_2.4.3#7]
Is it possible to get the **aura_env** functionality working in the TBC client?
https://github.com/WeakAuras/WeakAuras2/wiki/aura_env

**Comment by tomtko** [comment]
It's messy, but you can somewhat simulate this by adding a trigger to your aura that checks on the `PLAYER_ENTERING_WORLD` event and add your "aura_env" variables in there.

Example aura I made for Cruator Flare count:
https://pastebin.com/pMiJMpPc
